### ISSUE TITLE
[ERROR] when i want to install docker-compose

### ISSUE THREAD

**Issue by sautmanurung1** [saefullohmaslul/kuki#20]
![image](https://github.com/saefullohmaslul/kuki/assets/68042498/fbded28d-2257-4414-be72-535850d48d3e)

when i want to install docker compose in my local, i got error like that

**Comment by saufiroja** [comment]
Hmmm, itu kayanya salah import deh grpchandler nya, soalnya di interface grpchandler itu ada di folder interfaces bukan di todos lagi, coba ganti import nya

**Comment by sautmanurung1** [comment]
itu salah import nya dimana yahh mas?

**Comment by saufiroja** [comment]
> itu salah import nya dimana yahh mas?

di internal/pkg/app
ubah aja import nya yang awal nya di folder todos ke interfaces

**Comment by saefullohmaslul** [comment]
Wah iya bener, kemaren gw ubah interfacenya ke directory interfaces. Cuma belum sempet gw running

**Comment by sautmanurung1** [comment]
oke oke ntar saya coba update lagi code nya

**Comment by saefullohmaslul** [comment]
udah gw fix disini guys #22 
@sautmanurung1 @saufiroja
